---
# tasks file for roles/elk_cent

- name: Centos docker install
  yum:
    name: docker
    state: latest
    update_cache: yes

- name: elasticsearch image
  containers.podman.podman_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:7.10.1

- name: elasticsearch container
  containers.podman.podman_containers:
    containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        state: present
        ports:
          - "9400:9400"
        networks:
          - name: elastic

- name: kibana image
  containers.podman.podman_image:
    name: docker.elastic.co/kibana/kibana:7.10.1

- name: kibana container
  containers.podman.podman_containers:
    containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.10.1
        state: present
        ports:
          - "5602:5602"
        networks:
          - name: elastic

- name: logstash image
  containers.podman.podman_image:
    name: docker.elastic.co/logstash/logstash:7.10.1

- name: logstash container
  containers.podman.podman_containers:
    containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.10.1
        state: present
        ports:
          - "5044:5044"
        networks:
          - name: elastic
