---
# tasks file for roles/ubuntu
- name: grafana package
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_7.3.6_amd64.deb
  register: pkg_grafana

- name: depackage grafana
  dpkg_selections:
    name: grafana_7.3.6_amd64.deb
    selection: install
  when: pkg_grafana.changed

- name: install libfontconfig
  apt:
    name: libfontconfig1
    state: latest
    update_cache: yes

- name: install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes

- name: start grafana
  service:
    name: grafana-server
    state: started

- name: install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes

- name: start prometheus
  service:
    name: prometheus
    state: started

- name: influxdata key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: influxdata repo
  apt_repository:
    repo: 'deb https://repos.influxdata.com/ubuntu focal stable'
    state: present

- name: install telegraf
  apt:
    name: telegraf
    state: latest
    update_cache: yes

- name: start telegraf
  service:
    name: telegraf
    state: started
